modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId='clockmod'
version="1.0-1.19.2"
displayName="ClockMod"
authors="franko"
description="Mostra a schermo l'orologio sincronizzato ricevuto dal server."

[[dependencies.clockmod]]
modId="forge"
mandatory=true
versionRange="[43.4.13,)"
ordering="NONE"
side="BOTH"

[[dependencies.clockmod]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1,20)"
ordering="NONE"
side="BOTH"
